plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.7'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

sourceCompatibility = '17'

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	//mysql connector, Spring Boot 可以連到 MySQL 的「驅動程式」
	implementation 'com.mysql:mysql-connector-j'
	//加上 MyBatis
	implementation 'com.baomidou:mybatis-plus-spring-boot3-starter:3.5.14'
	// web
	implementation 'org.springframework.boot:spring-boot-starter-web'
	//security
	implementation 'org.springframework.boot:spring-boot-starter-security'
	// validation
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	// 尋找 MyBatis Spring Boot Starter 依賴
    //implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter'
    //ai
    implementation 'org.springframework.ai:spring-ai-starter-model-openai:1.0.1'
    implementation 'org.springframework.boot:spring-boot-devtools:3.5.3'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
